version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-cicd-demo-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7o9z8onsztn1"
s3_prefix = "sam-cicd-demo-dev"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
